# Generated by Django 4.1.3 on 2023-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("college", "__first__"),
        ("courses", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("onetID", models.CharField(default="", max_length=200)),
                ("median_salary", models.IntegerField(default=0)),
                ("industry", models.CharField(default="", max_length=200)),
                (
                    "popular_colleges",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="college.college",
                        verbose_name="colleges",
                    ),
                ),
                (
                    "useful_courses",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="courses.courses",
                        verbose_name="courses",
                    ),
                ),
            ],
        ),
    ]
