# Generated by Django 4.1.3 on 2023-01-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("icon", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                ("skills", models.ManyToManyField(to="Careers.skills")),
            ],
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dailyTasks", models.TextField()),
                ("description", models.TextField()),
                ("futureOutlook", models.FloatField()),
                ("requiresCollege", models.BooleanField()),
                ("requiresGradSchool", models.BooleanField()),
                ("majorID", models.IntegerField()),
                ("bullet_1", models.CharField(default=" ", max_length=250)),
                ("bullet_2", models.CharField(default=" ", max_length=250)),
                ("bullet_3", models.CharField(default=" ", max_length=250)),
                ("bullet_4", models.CharField(default=" ", max_length=250)),
                ("bullet_5", models.CharField(default=" ", max_length=250)),
                ("what_they_do", models.TextField(default=" ")),
                ("task_1", models.TextField(default=" ")),
                ("task_2", models.TextField(default=" ")),
                ("task_3", models.TextField(default=" ")),
                ("knowledge_1", models.CharField(default=" ", max_length=300)),
                ("knowledge_2", models.CharField(default=" ", max_length=300)),
                ("knowledge_3", models.CharField(default=" ", max_length=300)),
                ("knowledge_4", models.CharField(default=" ", max_length=300)),
                ("knowledge_5", models.CharField(default=" ", max_length=300)),
                ("knowledge_6", models.CharField(default=" ", max_length=300)),
                ("skills_1", models.CharField(default=" ", max_length=300)),
                ("skills_2", models.CharField(default=" ", max_length=300)),
                ("skills_3", models.CharField(default=" ", max_length=300)),
                ("skills_4", models.CharField(default=" ", max_length=300)),
                ("skills_5", models.CharField(default=" ", max_length=300)),
                ("abilities_1", models.CharField(default=" ", max_length=300)),
                ("abilities_2", models.CharField(default=" ", max_length=300)),
                ("abilities_3", models.CharField(default=" ", max_length=300)),
                ("abilities_4", models.CharField(default=" ", max_length=300)),
                ("abilities_5", models.CharField(default=" ", max_length=300)),
                ("abilities_6", models.CharField(default=" ", max_length=300)),
                ("abilities_7", models.CharField(default=" ", max_length=300)),
                ("char_1", models.CharField(default=" ", max_length=100)),
                ("char_2", models.CharField(default=" ", max_length=100)),
                ("char_3", models.CharField(default=" ", max_length=100)),
                ("char_4", models.CharField(default=" ", max_length=100)),
                ("char_5", models.CharField(default=" ", max_length=100)),
                ("char_6", models.CharField(default=" ", max_length=100)),
                ("tech_1", models.CharField(default=" ", max_length=100)),
                ("tech_2", models.CharField(default=" ", max_length=100)),
                ("tech_3", models.CharField(default=" ", max_length=100)),
                ("tech_4", models.CharField(default=" ", max_length=100)),
                ("tech_5", models.CharField(default=" ", max_length=100)),
                ("avg_degree", models.CharField(default=" ", max_length=100)),
                ("annual_10th", models.IntegerField(default=0)),
                ("annual_median", models.IntegerField(default=0)),
                ("annual_90th", models.IntegerField(default=0)),
                ("hourly_10th", models.IntegerField(default=0)),
                ("hourly_median", models.IntegerField(default=0)),
                ("hourly_90th", models.IntegerField(default=0)),
                ("num_states_above", models.IntegerField(default=0)),
                ("num_states_avg", models.IntegerField(default=0)),
                ("num_states_below", models.IntegerField(default=0)),
                ("industry_1_name", models.CharField(default=" ", max_length=300)),
                ("industry_1_percent", models.IntegerField(default=0)),
                ("industry_2_name", models.CharField(default=" ", max_length=300)),
                ("industry_2_percent", models.IntegerField(default=0)),
                ("industry_3_name", models.CharField(default=0, max_length=300)),
                ("industry_3_percent", models.IntegerField(default=0)),
                (
                    "above_avg_states",
                    models.ManyToManyField(blank=True, to="Careers.states"),
                ),
                (
                    "industryID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Careers.industry",
                    ),
                ),
                (
                    "similar_careers",
                    models.ManyToManyField(blank=True, to="Careers.career"),
                ),
                ("skills", models.ManyToManyField(to="Careers.skills")),
            ],
        ),
    ]
