# Generated by Django 3.2.13 on 2022-09-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('skills', models.ManyToManyField(to='Careers.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dailyTasks', models.TextField()),
                ('description', models.TextField()),
                ('futureOutlook', models.FloatField()),
                ('requiresCollege', models.BooleanField()),
                ('requiresGradSchool', models.BooleanField()),
                ('majorID', models.IntegerField()),
                ('industryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Careers.industry')),
            ],
        ),
    ]
