# Generated by Django 4.1.3 on 2023-02-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="education",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
