# Generated by Django 3.2.13 on 2022-09-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(to='Careers.Skills'),
        ),
    ]
