# Generated by Django 4.1.3 on 2023-02-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Careers", "0002_career_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career", old_name="name", new_name="career_name",
        ),
        migrations.RenameField(
            model_name="career", old_name="onetID", new_name="onet_id",
        ),
    ]
