# Generated by Django 4.1.3 on 2023-01-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("college", "__first__"),
        ("School", "__first__"),
        ("Careers", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomplishments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("leadership", models.BooleanField()),
                ("schoolAward", models.BooleanField()),
                ("stateAward", models.BooleanField()),
                ("nationalAward", models.BooleanField()),
                ("competition", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="userAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=60, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("firstName", models.CharField(max_length=35)),
                ("lastName", models.CharField(max_length=35)),
                (
                    "year",
                    models.IntegerField(
                        choices=[(9, "9th"), (10, "10th"), (11, "11th"), (12, "12th")],
                        default=9,
                    ),
                ),
                ("wantsCollege", models.BooleanField(null=True)),
                ("gpa", models.FloatField(null=True)),
                ("numHonorsClasses", models.IntegerField(null=True)),
                ("numAPClasses", models.IntegerField(null=True)),
                ("numIBClasses", models.IntegerField(null=True)),
                ("numDEClasses", models.IntegerField(null=True)),
                ("familyIncome", models.IntegerField(null=True)),
                ("maxSpending", models.IntegerField(null=True)),
                ("sat", models.IntegerField(null=True)),
                ("satAttempts", models.IntegerField(null=True)),
                ("act", models.IntegerField(null=True)),
                (
                    "accomplishments",
                    models.ManyToManyField(to="userAccount.accomplishments"),
                ),
                (
                    "desiredIndustry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Careers.industry",
                    ),
                ),
                (
                    "favCareer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favCareer",
                        to="Careers.career",
                    ),
                ),
                (
                    "likedCareers",
                    models.ManyToManyField(
                        related_name="likedCareers", to="Careers.career"
                    ),
                ),
                ("likedSchools", models.ManyToManyField(to="college.college")),
                (
                    "recommendedCareers",
                    models.ManyToManyField(
                        related_name="recommendedCareers", to="Careers.career"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="School.school",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
