# Generated by Django 4.1.1 on 2022-09-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("highSchoolCourses", "0001_initial"),
        ("Careers", "0001_initial"),
        ("college", "0001_initial"),
        ("School", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomplishments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("leadership", models.BooleanField()),
                ("schoolAward", models.BooleanField()),
                ("stateAward", models.BooleanField()),
                ("nationalAward", models.BooleanField()),
                ("competition", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="userAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=60, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("firstName", models.CharField(max_length=35)),
                ("lastName", models.CharField(max_length=35)),
                (
                    "year",
                    models.IntegerField(
                        choices=[(9, "9th"), (10, "10th"), (11, "11th"), (12, "12th")],
                        default=9,
                    ),
                ),
                ("wantsCollege", models.BooleanField()),
                ("gpa", models.FloatField()),
                ("numHonorsClasses", models.IntegerField()),
                ("numAPClasses", models.IntegerField()),
                ("numIBClasses", models.IntegerField()),
                ("numDEClasses", models.IntegerField()),
                ("familyIncome", models.IntegerField()),
                ("maxSpending", models.IntegerField()),
                ("sat", models.IntegerField()),
                ("satAttempts", models.IntegerField()),
                ("act", models.IntegerField()),
                (
                    "accomplishments",
                    models.ManyToManyField(to="userAccount.accomplishments"),
                ),
                (
                    "desiredIndustry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Careers.industry",
                    ),
                ),
                ("likedCareers", models.ManyToManyField(to="Careers.career")),
                ("likedSchools", models.ManyToManyField(to="college.college")),
                (
                    "prevCourses",
                    models.ManyToManyField(to="highSchoolCourses.highschoolcourses"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="School.school",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
