# Generated by Django 4.1.3 on 2023-02-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("college", "0001_initial"),
        ("School", "0001_initial"),
        ("Careers", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomplishments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("leadership", models.BooleanField()),
                ("schoolAward", models.BooleanField()),
                ("stateAward", models.BooleanField()),
                ("nationalAward", models.BooleanField()),
                ("competition", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="userAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(max_length=60, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("firstName", models.CharField(blank=True, max_length=35)),
                ("lastName", models.CharField(blank=True, max_length=35)),
                (
                    "year",
                    models.IntegerField(
                        choices=[(9, "9th"), (10, "10th"), (11, "11th"), (12, "12th")],
                        default=9,
                    ),
                ),
                ("wantsCollege", models.BooleanField(blank=True, null=True)),
                ("gpa", models.FloatField(blank=True, null=True)),
                ("numHonorsClasses", models.IntegerField(blank=True, null=True)),
                ("numAPClasses", models.IntegerField(blank=True, null=True)),
                ("numIBClasses", models.IntegerField(blank=True, null=True)),
                ("numDEClasses", models.IntegerField(blank=True, null=True)),
                ("familyIncome", models.IntegerField(blank=True, null=True)),
                ("maxSpending", models.IntegerField(blank=True, null=True)),
                ("sat", models.IntegerField(blank=True, null=True)),
                ("satAttempts", models.IntegerField(blank=True, null=True)),
                ("act", models.IntegerField(blank=True, null=True)),
                (
                    "accomplishments",
                    models.ManyToManyField(
                        blank=True, to="userAccount.accomplishments"
                    ),
                ),
                (
                    "dislikedCareers",
                    models.ManyToManyField(
                        blank=True, related_name="dislikedCareers", to="Careers.career"
                    ),
                ),
                (
                    "dislikedCourses",
                    models.ManyToManyField(
                        blank=True, related_name="dislikedCourses", to="courses.courses"
                    ),
                ),
                (
                    "dislikedSchools",
                    models.ManyToManyField(
                        blank=True,
                        related_name="DislikedColleges",
                        to="college.college",
                    ),
                ),
                (
                    "favCareer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favCareer",
                        to="Careers.career",
                    ),
                ),
                (
                    "favoriteSchool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favoriteSchool",
                        to="college.college",
                    ),
                ),
                (
                    "likedCareers",
                    models.ManyToManyField(
                        blank=True, related_name="likedCareers", to="Careers.career"
                    ),
                ),
                (
                    "likedCourses",
                    models.ManyToManyField(
                        blank=True, related_name="likedCourses", to="courses.courses"
                    ),
                ),
                (
                    "likedSchools",
                    models.ManyToManyField(
                        blank=True, related_name="LikedColleges", to="college.college"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="School.school",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
