# Generated by Django 4.1.3 on 2023-01-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("college", "0002_remove_college_city_remove_college_description_and_more"),
        ("Careers", "0001_initial"),
        ("userAccount", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="recommendedCareers",),
        migrations.AddField(
            model_name="useraccount",
            name="dislikedCareers",
            field=models.ManyToManyField(
                related_name="dislikedCareers", to="Careers.career"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="dislikedCourses",
            field=models.ManyToManyField(
                related_name="dislikedCourses", to="courses.courses"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="dislikedSchools",
            field=models.ManyToManyField(
                related_name="DislikedColleges", to="college.college"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="favoriteSchool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favoriteSchool",
                to="college.college",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="likedCourses",
            field=models.ManyToManyField(
                related_name="likedCourses", to="courses.courses"
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="likedSchools",
            field=models.ManyToManyField(
                related_name="LikedColleges", to="college.college"
            ),
        ),
    ]
