# Generated by Django 4.1.1 on 2022-09-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="wantsCollege",
            field=models.BooleanField(blank=True),
        ),
    ]
