# Generated by Django 4.1.3 on 2023-02-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0002_remove_useraccount_recommendedcareers_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="desiredIndustry",),
    ]
