# Generated by Django 4.1.1 on 2022-09-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0002_alter_useraccount_wantscollege"),
    ]

    operations = [
        migrations.RemoveField(model_name="useraccount", name="wantsCollege",),
    ]
