# Generated by Django 4.1.1 on 2022-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0003_remove_useraccount_wantscollege"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount", name="gpa", field=models.FloatField(null=True),
        ),
    ]
