# Generated by Django 4.1.1 on 2022-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0004_alter_useraccount_gpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="wantsCollege",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount", name="act", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="familyIncome",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="maxSpending",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="numAPClasses",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="numDEClasses",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="numHonorsClasses",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="numIBClasses",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount", name="sat", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="satAttempts",
            field=models.IntegerField(null=True),
        ),
    ]
