# Generated by Django 4.1.1 on 2022-09-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("State", "0001_initial"),
        ("duelEnrollmentCourses", "0001_initial"),
        ("highSchoolCourses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=175)),
                ("DEallowed", models.BooleanField()),
                ("schoolAddress", models.CharField(max_length=350)),
                ("englishUnits", models.IntegerField()),
                ("mathUnits", models.IntegerField()),
                ("scienceUnits", models.IntegerField()),
                ("socialStudiesUnits", models.IntegerField()),
                ("humanityUnits", models.IntegerField()),
                ("CTAEunits", models.IntegerField()),
                ("languageUnits", models.IntegerField()),
                ("fineArtsUnits", models.IntegerField()),
                ("CtaeLanguageFineArtsUnits", models.IntegerField()),
                ("healthPEUnits", models.IntegerField()),
                ("academicElectiveUnits", models.IntegerField()),
                ("freeElectiveUnits", models.IntegerField()),
                (
                    "courses",
                    models.ManyToManyField(to="highSchoolCourses.highschoolcourses"),
                ),
                (
                    "deSchools",
                    models.ManyToManyField(
                        to="duelEnrollmentCourses.duelenrollmentschool"
                    ),
                ),
                (
                    "stateID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="State.state",
                    ),
                ),
            ],
        ),
    ]
