# Generated by Django 4.1.3 on 2023-01-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("School", "0002_remove_school_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="schoolCourses",
            field=models.ManyToManyField(
                related_name="SchoolCourses", to="courses.courses"
            ),
        ),
    ]
