# Generated by Django 4.1.1 on 2022-09-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("public", models.BooleanField(default=True)),
                ("year_est", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
