# Generated by Django 3.2.13 on 2022-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('public', models.BooleanField(default=True)),
                ('year_est', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
