# Generated by Django 4.1.3 on 2023-01-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="college", name="city",),
        migrations.RemoveField(model_name="college", name="description",),
        migrations.RemoveField(model_name="college", name="public",),
        migrations.RemoveField(model_name="college", name="year_est",),
        migrations.AddField(
            model_name="college",
            name="collegeAIKey",
            field=models.IntegerField(null=True),
        ),
    ]
