# Generated by Django 4.1.1 on 2023-03-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="college",
            name="acceptance_rate",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="college",
            name="average_fin_aid",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="college",
            name="sat_score",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="college",
            name="ten_year_earnings",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="college",
            name="collegeAIKey",
            field=models.IntegerField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="college",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
