# Generated by Django 4.1.3 on 2023-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendedCareers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("careerID", models.IntegerField()),
                ("similarity", models.FloatField()),
            ],
        ),
    ]
