# Generated by Django 4.1.1 on 2022-09-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="highSchoolCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courseName", models.CharField(max_length=75)),
                ("AP", models.BooleanField(default=False)),
                ("courseScore", models.FloatField()),
                ("english", models.BooleanField(default=False)),
                ("science", models.BooleanField(default=False)),
                ("socialStudies", models.BooleanField(default=False)),
                ("math", models.BooleanField(default=False)),
                ("humanity", models.BooleanField(default=False)),
                ("CTAE", models.BooleanField(default=False)),
                ("language", models.BooleanField(default=False)),
                ("fineArts", models.BooleanField(default=False)),
                ("health_PE", models.BooleanField(default=False)),
                ("preReqID", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
