# Generated by Django 4.1.1 on 2022-10-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highSchoolCourses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="highschoolcourses",
            name="desciption",
            field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="highschoolcourses",
            name="difficulty",
            field=models.FloatField(default=0),
        ),
    ]
