# Generated by Django 3.2.13 on 2022-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highSchoolCourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolcourses',
            name='preReqID',
            field=models.IntegerField(null=True),
        ),
    ]
