# Generated by Django 3.2.13 on 2022-09-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highSchoolCourses', '0002_alter_highschoolcourses_prereqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolcourses',
            name='preReqID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
