# Generated by Django 4.1 on 2023-01-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CareerSurveyOneAnswers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="careersurveyoneanswers",
            old_name="survey",
            new_name="questionID",
        ),
        migrations.RemoveField(
            model_name="careersurveyoneanswers",
            name="question",
        ),
        migrations.RemoveField(
            model_name="careersurveyoneanswers",
            name="user",
        ),
        migrations.AddField(
            model_name="careersurveyoneanswers",
            name="userID",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="careersurveyoneanswers",
            name="answer",
            field=models.CharField(default="", max_length=100),
        ),
    ]
