# Generated by Django 4.1 on 2023-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CareerSurveyOneAnswers",
            "0002_rename_survey_careersurveyoneanswers_questionid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersurveyoneanswers",
            name="questionID",
            field=models.CharField(default="", max_length=100),
        ),
    ]
