# Generated by Django 4.1 on 2023-01-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerSurveyOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secondary_school",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "tertiary_school",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "independent_job",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "work_from_home",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "favorite_subject",
                    models.CharField(
                        choices=[
                            ("MTH", "Mathematics"),
                            ("HIS", "History"),
                            ("SCI", "Sciences"),
                            ("ENG", "English & Literature"),
                            ("ART", "Humanities & Arts"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "favorite_careers",
                    models.IntegerField(
                        choices=[
                            ("BF", "Business and finance"),
                            ("HS", "Healthcare and science"),
                            ("ESS", "Education and social services"),
                            ("MCE", "Manufacturing, construction and engineering"),
                            ("MAE", "Media, arts, and entertainment"),
                            ("RHT", "Retail, hospitality, and tourism"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "shifting_schedule",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "socializing_more",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "sports_as_career",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
                (
                    "travel_for_work",
                    models.IntegerField(choices=[(0, "No"), (1, "Yes")]),
                ),
            ],
        ),
    ]
