# Generated by Django 4.1 on 2023-01-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CareerSurveyOne", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careersurveyone",
            name="favorite_careers",
            field=models.CharField(
                choices=[
                    ("BF", "Business and finance"),
                    ("HS", "Healthcare and science"),
                    ("ESS", "Education and social services"),
                    ("MCE", "Manufacturing, construction and engineering"),
                    ("MAE", "Media, arts, and entertainment"),
                    ("RHT", "Retail, hospitality, and tourism"),
                ],
                max_length=3,
            ),
        ),
    ]
