# Generated by Django 4.1 on 2023-01-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CareerSurveyOne", "0002_alter_careersurveyone_favorite_careers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careersurveyone",
            name="favorite_careers",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="favorite_subject",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="independent_job",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="secondary_school",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="shifting_schedule",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="socializing_more",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="sports_as_career",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="tertiary_school",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="travel_for_work",
        ),
        migrations.RemoveField(
            model_name="careersurveyone",
            name="work_from_home",
        ),
        migrations.AddField(
            model_name="careersurveyone",
            name="question",
            field=models.CharField(default="", max_length=100),
        ),
    ]
