# Generated by Django 4.1.3 on 2023-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField(blank=True, default=0)),
                ("careerID", models.IntegerField(blank=True, default=0)),
                ("score", models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
