# Generated by Django 3.2.13 on 2023-03-07 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='missions/')),
                ('count', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
