# Generated by Django 4.1.1 on 2022-09-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="duelEnrollmentCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("courseScore", models.FloatField()),
                ("preReqID", models.IntegerField(blank=True)),
                ("english", models.BooleanField()),
                ("science", models.BooleanField()),
                ("socialStudies", models.BooleanField()),
                ("math", models.BooleanField()),
                ("humanity", models.BooleanField()),
                ("language", models.BooleanField()),
                ("fineArts", models.BooleanField()),
                ("earlyChildhood", models.BooleanField()),
                ("cyberSecurity", models.BooleanField()),
                ("digitalMedia", models.BooleanField()),
                ("it", models.BooleanField()),
                ("emt", models.BooleanField()),
                ("healthTech", models.BooleanField()),
                ("nursing", models.BooleanField()),
                ("carpentry", models.BooleanField()),
                ("electrician", models.BooleanField()),
                ("hvac", models.BooleanField()),
                ("machining", models.BooleanField()),
                ("weilding", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="duelEnrollmentSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("address", models.CharField(max_length=200)),
                (
                    "courses",
                    models.ManyToManyField(
                        to="duelEnrollmentCourses.duelenrollmentcourses"
                    ),
                ),
            ],
        ),
    ]
